import { runNormalizerTests } from "./unit/normalizers.test";
import { runTreatmentCourseTests } from "./unit/treatment-course.test";
import { runSchedulingTests } from "./unit/scheduling.test";
import { runMigrationTests } from "./unit/migration.test";
import { runMultiClinicTests } from "./unit/multi-clinic.test";
import { runStaffManagementTests } from "./unit/staff-management.test";
import { runAuthResolverTests } from "./unit/auth-resolver.test";
import { runStaffResolverTests } from "./unit/staff-resolver.test";
import { runClinicResolverTests } from "./unit/clinic-resolver.test";
import { runRoleResolverTests } from "./unit/role-resolver.test";
import { runSignInTests } from "./unit/sign-in.test";
import { runClinicContextTests } from "./unit/clinic-context.test";
import { runSignOutTests } from "./unit/sign-out.test";
import { runRouteGateTests } from "./unit/route-gate.test";
import { runApplicationAccessTests } from "./unit/application-access.test";
import { runActionAuthorizationTests } from "./unit/action-authorization.test";
import { runStaffGovernanceTests } from "./unit/staff-governance.test";
import { runPasswordRecoveryTests } from "./unit/password-recovery.test";
import { runUsernameSchemaTests } from "./unit/username-schema.test";
import { runLinkStaffDirectRpcTests } from "./unit/link-staff-direct-rpc.test";
import { runDirectProvisioningServiceTests } from "./unit/direct-provisioning-service.test";
import { runAdminResetPasswordTests } from "./unit/admin-reset-password.test";
import { runFinalizeResetRpcTests } from "./unit/finalize-reset-rpc.test";
import { runAssignUsernameRpcTests } from "./unit/assign-username-rpc.test";
import { runLegacyUsernameAppTests } from "./unit/legacy-username-app.test";
import { runStaffAuthUiTests } from "./unit/staff-auth-ui.test";
import { runShellIdentityTests } from "./unit/shell-identity.test";
import { runReceptionClinicalHandoffTests } from "./unit/reception-clinical-handoff.test";
import { runTreatmentSessionPlansMigration32Tests } from "./unit/treatment-session-plans-migration32.test";
import { runSaveTreatmentSessionPlanRpc33Tests } from "./unit/save-treatment-session-plan-rpc33.test";
import { runDoctorOccurrencePlanUiTests } from "./unit/doctor-occurrence-plan-ui.test";
import { runAntdReceptionShellTests } from "./unit/antd-reception-shell.test";
import { runAntdStaffUiTests } from "./unit/antd-staff-ui.test";
import { runAntdPatientMasterTests } from "./unit/antd-patient-master.test";
import { runAntdReceptionModalTests } from "./unit/antd-reception-modal.test";
import { runAtomicReceptionIntakeRpcTests } from "./unit/atomic-reception-intake-rpc.test";
import { runReceptionTimezoneTests } from "./unit/reception-timezone.test";
import { runScheduleTimezoneTests } from "./unit/schedule-timezone.test";
import { runLoginAntdRedesignTests } from "./unit/login-antd-redesign.test";
import { runSelectClinicRedesignTests } from "./unit/select-clinic-redesign.test";
import { runClinicSelectionUxTests } from "./unit/clinic-selection-ux.test";
import { runDashboardAntdRedesignTests } from "./unit/dashboard-antd-redesign.test";
import { runAuthClinicAutoEnterFixTests } from "./unit/auth-clinic-autoenter-fix.test";
import { runDoctorClinicalCourseUiTests } from "./unit/doctor-clinical-course-ui.test";
import { runDiagnosisCatalogTt06ImportTests } from "./unit/diagnosis-catalog-tt06-import.test";
import { runDiagnosisDvktTemplateStageBTests } from "./unit/diagnosis-dvkt-template-stageb.test";
import { runTt06TemplateRlsTests } from "./unit/tt06-template-rls.test";
import { runDoctorTt06SuggestionUiTests } from "./unit/doctor-tt06-suggestion-ui.test";
import { runDoctorPatientChartWorkspaceTests } from "./unit/doctor-patient-chart-workspace.test";
import { runClinicalMasterDiagnosisManagementTests } from "./unit/clinical-master-diagnosis-management.test";
import { runAuthProtectedPageLogoutStabilityTests } from "./unit/auth-protected-page-logout-stability.test";
import { runClinicalMasterDiagnosisProductionHardeningTests } from "./unit/clinical-master-diagnosis-production-hardening.test";

async function main() {
  try {
    runNormalizerTests();
    runTreatmentCourseTests();
    runSchedulingTests();
    runMigrationTests();
    runMultiClinicTests();
    await runStaffManagementTests();
    runAuthResolverTests();
    runStaffResolverTests();
    runClinicResolverTests();
    runRoleResolverTests();
    await runSignInTests();
    runClinicContextTests();
    runSignOutTests();
    runRouteGateTests();
    runApplicationAccessTests();
    runActionAuthorizationTests();
    runStaffGovernanceTests();
    await runPasswordRecoveryTests();
    runUsernameSchemaTests();
    runLinkStaffDirectRpcTests();
    await runDirectProvisioningServiceTests();
    await runAdminResetPasswordTests();
    runFinalizeResetRpcTests();
    runAssignUsernameRpcTests();
    await runLegacyUsernameAppTests();
    runStaffAuthUiTests();
    runShellIdentityTests();
    runReceptionClinicalHandoffTests();
    runTreatmentSessionPlansMigration32Tests();
    runSaveTreatmentSessionPlanRpc33Tests();
    runDoctorOccurrencePlanUiTests();
    runAntdReceptionShellTests();
    runAntdStaffUiTests();
    runAntdPatientMasterTests();
    runAntdReceptionModalTests();
    await runAtomicReceptionIntakeRpcTests();
    await runReceptionTimezoneTests();
    await runScheduleTimezoneTests();
    runLoginAntdRedesignTests();
    runSelectClinicRedesignTests();
    runClinicSelectionUxTests();
    runDashboardAntdRedesignTests();
    runAuthClinicAutoEnterFixTests();
    runDoctorClinicalCourseUiTests();
    await runDiagnosisCatalogTt06ImportTests();
    await runDiagnosisDvktTemplateStageBTests();
    await runTt06TemplateRlsTests();
    await runDoctorTt06SuggestionUiTests();
    runDoctorPatientChartWorkspaceTests();
    await runClinicalMasterDiagnosisManagementTests();
    await runAuthProtectedPageLogoutStabilityTests();
    await runClinicalMasterDiagnosisProductionHardeningTests();
    console.log("All unit test suites executed successfully.");
  } catch (err) {
    console.error("Test failure:", err);
    process.exit(1);
  }
}

main();
